# Site settings
title: "vue.js / nuxt.js"
author: "Kim Yoon Sung"
description: ""
keywords: ""
biography: ""
colophon: ""

baseurl: 
url:

twitter_username:
github_username:
linkedin_username:
facebook_username:
google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
